### ISSUE TITLE
Fix doc 0008 embedded file name 

### ISSUE THREAD

**Issue by JervyShi** [wascc/adr#8]
![image](https://user-images.githubusercontent.com/1862729/126730110-3420c865-3dfc-454e-949b-031f4932cb44.png)

Document `0008-embedded` Naming is not as expected and a 404 pages occurs when accessing.

**Comment by brooksmtownsend** [comment]
https://wasmcloud.github.io/adr/0008-embedded.html is live for me, please let me know if it's inaccessible again and we can re-open this.
